### ISSUE TITLE
LBNet not working in Windows 11

### ISSUE THREAD

**Issue by fearworksmedia** [iversc/lbnet#6]
I am finding that LBNet is not working in Windows 11, at least not when using it to act as a client. For example, usign LBNet to download a web page results in a connection error.

**Comment by fearworksmedia** [comment]
I have been looking to this further and I stumbled upon this page:

https://stackoverflow.com/questions/69856792/winsock-connect-fails-with-wsaefault-error-on-windows-11-only/69859627

I changed all instance of AF_UNSPEC to AF_INET just to test with IPv4 only and it seems to work. I'm not claiming I've found the problem as there may be more to it than I can fathom, but this certainly seems to be along the right lines. I guess implementing the dual-stack socket rather than using AF_UNSPEC might be necessary to make the DLL compatible with Windows 11?

**Comment by iversc** [comment]
Looks like I'm actually misusing AF_UNSPEC when creating the socket - it's only supposed to be used for the call to getaddrinfo(), as far as I can tell, now.

I'll see if I can get a quick correction for this.

**Comment by fearworksmedia** [comment]
Sounds good, I can test on my Windows 11 VM as soon as you think it might be sorted :)

**Comment by iversc** [comment]
Do you want me to make a build for you?  Or do you want to just pull the code and compile or yourself?  Or make the change yourself and build, there's only two lines that actually need to change to fix this.

If you want to do it yourself, there's two lines in LBNet.cpp that are both:

`s = socket(AF_UNSPEC, socktype, protocol);`

Just replace both lines with the following:

`s = socket(ptr->ai_family, ptr->ai_socktype, ptr->ai_protocol);`

EDIT: clipboard failed to copy.

**Comment by fearworksmedia** [comment]
I'll give it a go now, I can change and build and let you know the result. Give me a few mins.

**Comment by fearworksmedia** [comment]
I can confirm that seems to have sorted the issue. It seems to be fine on Windows 11 now and I'm not seeing the connection error at all.

Time for a new release :)

**Comment by fearworksmedia** [comment]
Been using this now for a few days on Windows 11 and have had no issues. That fix has definitely sorted the issue I was experiencing.
